### ISSUE TITLE
SIGSEGV in script_runner

### ISSUE THREAD

**Issue by Aareon** [Aareon/Pyto#2]
```
Traceback (most recent call last):
  File "Library/python38/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "Library/python38/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "Pyto.app/scripts_runner.py", line 51, in run
    super().run()
  File "Library/python38/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "Pyto.app/Lib/console.py", line 620, in run_script
    t = run()
  File "Pyto.app/Lib/console.py", line 475, in run
    spec.loader.exec_module(__script__)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_modul
e
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_r
emoved
  File "Documents/untitled folder/opencvtest.py", line 37, in <module>
    cv.imshow('img1', img1)
  File "../compiled/cv2/__init__.py", line 43, in imshow_image
  File "Pyto.app/site-packages/PIL/Image.py", line 2205, in show
    _show(self, title=title, command=command)
  File "Pyto.app/site-packages/PIL/Image.py", line 3167, in _show
    _showxv(image, **options)
  File "Pyto.app/site-packages/PIL/Image.py", line 3181, in _showxv
    ImageShow.show(image, title, **options)
  File "<string>", line 182, in show_image
  File "Pyto.app/Lib/_opencv_view.py", line 29, in show
    view = OpenCVView()
  File "Pyto.app/Lib/_opencv_view.py", line 16, in __init__
    self.background_color = ui.COLOR_SYSTEM_BACKGROUND
  File "Pyto.app/Lib/pyto_ui.py", line 2578, in __setattr__
    super().__setattr__(name, value)
  File "Pyto.app/Lib/pyto_ui.py", line 2996, in background_color
    self.__py_view__.backgroundColor = new_value.__py_color__
  File "Pyto.app/Lib/rubicon/objc/api.py", line 671, in __setattr__
    ObjCBoundMethod(method, self)(value)
  File "Pyto.app/Lib/rubicon/objc/api.py", line 249, in __call__
    return self.method(self.receiver, *args, **kwargs)
  File "Pyto.app/Lib/rubicon/objc/api.py", line 168, in __call__
    result = f(receiver, self.selector, *converted_args)
  File "Pyto.app/Lib/rubicon/objc/api.py", line 275, in __call__
    result = self.py_method(py_self, *args)
  File "Pyto.app/scripts_runner.py", line 87, in runCode_
    exec(str(code))
  File "<string>", line 5, in <module>
Thread-13 crashed with signal: SIGSEGV
```
Report received from Discord user
iPadOS 14.6 (18F72)

**Comment by elian** [comment]
I get somthing similar on the second run of my script (using objc python):

Traceback (most recent call last):
  File "Library/python38/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "Library/python38/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "Pyto.app/scripts_runner.py", line 51, in run
    super().run()
  File "Library/python38/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "Pyto.app/Lib/console.py", line 325, in run_script
    __clear_mods__()
  File "Pyto.app/Lib/console.py", line 264, in __clear_mods__
    delattr(_values, attr)
  File "Pyto.app/Lib/pyto_ui.py", line 2555, in __del__
    if self.__py_view__.references == 1:
  File "Pyto.app/Lib/rubicon/objc/api.py", line 617, in __getattr__
    method = self.objc_class._cache_property_accessor(name)
  File "Pyto.app/Lib/rubicon/objc/api.py", line 516, in objc_class
    return ObjCClass(libobjc.object_getClass(self))
  File "Pyto.app/Lib/rubicon/objc/api.py", line 817, in __new__
    ptr, name = cls._new_from_ptr(name_or_ptr)
  File "Pyto.app/Lib/rubicon/objc/api.py", line 718, in _new_from_ptr
    elif not object_isClass(ptr):

File "Pyto.app/Lib/rubicon/objc/api.py", line 275, in __call__
    result = self.py_method(py_self, *args)
  File "Pyto.app/scripts_runner.py", line 87, in runCode_
    exec(str(code))
  File "<string>", line 5, in <module>
Thread-13 crashed with signal: SIGSEGV

**Comment by Aareon** [comment]
Thanks for reporting this @elian. Perhaps the nice people over at rubicon can assist. I'll look into it a little more before I open an issue over there.
